#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pp'
require 'open3'
require 'yaml'
require 'base64'

abort 'Provide secret file|name' if ARGV.empty?
secret_file_or_name = ARGV[0]

yml = if File.exist? secret_file_or_name
        File.read secret_file_or_name
      else
        cmd = "kubectl get secret #{secret_file_or_name} -o yaml"
        out, err, st = Open3.capture3 cmd
        abort "ERR: #{err} #{st}" unless st.success?
        out
      end

secrets = YAML.safe_load(yml)['data']
secrets.each do |k, v|
  puts format('%s: %s', k, Base64.decode64(v))
end
